### ISSUE TITLE
ExampleControl test

### ISSUE THREAD

**Issue by FilippoFer** [Beckhoff/TE2000_Client_Samples#2]
Hi,

I was testing the ExampleControl test that uses jasmine. I would like to report that:

1. In the jasmine-browser.js there is this part of the code:
  // This files contains the test itself
  specDir: "spec",
  specFiles: ["**/*[sS]pec.js"],
  
  but the of the spec file is "mainSpec.js" so the file is not taken. I had to rename it mainsSpec for example.
  
  2. In the mainSpec.js file the ExampleControl is not recognized. Is this a problem?
  
![2024-10-17_15-11-09](https://github.com/user-attachments/assets/bf8b3345-08ef-4161-a831-9489b6aca416)

I had to add the ExampleControl project as NuGet package to get right.

3. In the ReadMe.md there is this line:
- [spec/ColorChange/ColorChange.ts](spec/ColorChange/ColorChange.ts) contains the control test itself.

But the file in the "spec" folder is not called like this

4. After changing the "spec" file as mainsSpec.js something is showing in the jasmine browser. Is it correct?

![2024-10-17_15-16-40](https://github.com/user-attachments/assets/fa55f5cb-0301-48a7-b0b7-80998c314145)

**Comment by HolgerJeromin** [comment]
Thanks for your feedback. 
I will give feedback / take care of it in the next days. 
Sorry for the delay.

**Comment by HolgerJeromin** [comment]
> 1. In the jasmine-browser.js there is this part of the code:
> // This files contains the test itself
> specDir: "spec",
> specFiles: ["**/*[sS]pec.js"],
> but the of the spec file is "mainSpec.js" so the file is not taken. I had to rename it mainsSpec for example.

The `specFiles` entry is a [RegExp](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp). So it matches every file which ends with `spec.js` or `Spec.js`. I just retested that and it worked here...

> 2. In the mainSpec.js file the ExampleControl is not recognized. Is this a problem?

I think this is a problem only before the first build of the project. After a build I see this:
![image](https://github.com/user-attachments/assets/d1892791-d2b4-462b-81b5-f545ec8e7b3a)

Perhaps you need to reopen the window. We see this sometimes with VisualStudio.

> 3. In the ReadMe.md there is this line:
> `spec/ColorChange/ColorChange.ts` contains the control test itself.

Thanks! Will fix the link.

> 4. After changing the "spec" file as mainsSpec.js something is showing in the jasmine browser. Is it correct?

The provided screenshot shows the expected output, yes.

Are you fine with closing this github issue?

**Comment by FilippoFer** [comment]
Hi Holger,

Thanks for all the clear answers. Yes, we can close the GitHub issue

Cordiali saluti/Best Regards,

Filippo Ferrario
Technical Support Engineer
+39 331 6857488
***@***.******@***.***>

Beckhoff Automation s.r.l.
Via Luciano Manara, 2
20812 Limbiate, MB
Italia
www.beckhoff.com<http://www.beckhoff.com/>

Seguici su: LinkedIn<https://www.linkedin.com/company/beckhoff-italia/> | Instagram<https://www.instagram.com/beckhoff_italia/> | Facebook<https://www.facebook.com/BeckhoffItalia>


This email contains confidential information. If you have received it in error, you must not read, use, copy or pass on this e-mail or its attachments.
If you have received the e-mail in error, please inform me immediately by reply e-mail and then delete this e-mail from your system. Thank you

Diese E-Mail enthaelt vertrauliche Informationen. Sollten Sie sie irrtuemlich erhalten haben, duerfen Sie diese E-Mail oder ihre Anhaenge nicht lesen, verwenden, kopieren oder weitergeben.
Sollten Sie die Mail versehentlich erhalten haben, teilen Sie mir dies bitte umgehend per Antwort-E-Mail mit und loeschen Sie diese E-Mail dann aus Ihrem System. Vielen Dank
